# Generated by Django 5.2.7 on 2025-11-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='metacritic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
