# Generated by Django 5.2.7 on 2025-11-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_metacritic'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
