# Generated by Django 5.2.7 on 2025-11-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='minimum_requirements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='recommended_requirements',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
